### PR TITLE
Add nano and vim syntax files

### PR DESCRIPTION
**Pull request by rbberger**
This adds syntax highlighting files for both `nano` and `vim`.

### CODE REVIEW

**Comment by rbberger** [comment]
@markeganfuller I'm moving the files from my own repo in here too, please have a look.

**Comment by markeganfuller** [comment]
Tested the Vim files and they are all ok. Would you mind changing the `CONTRIBUTORS.md` to use my personal email : `markeganfuller@googlemail.com`. Then its inline with my entry in the Singularity contrib file.

**Review by vsoch — COMMENTED** [review]
Awesome! I'll do the changes and merge from local.

**Comment by vsoch** [comment]
The nanorc doesn't work for me on ubuntu - is this some kind of OSx flavor?

**Comment by vsoch** [comment]
```
Error in /home/vanessa/.nano/singularity.nanorc on line 4: Regex strings must begin and end with a " character

Error in /home/vanessa/.nano/singularity.nanorc on line 6: Command "comment" not understood

Error in /home/vanessa/.nano/singularity.nanorc on line 24: Color "normal" not understood.
Valid colors are "green", "red", "blue",
"white", "yellow", "cyan", "magenta" and
"black", with the optional prefix "bright"
for foreground colors.
```

**Comment by vsoch** [comment]
okay figured it out! The name of the syntax needed to be in quotes, see this issue https://savannah.gnu.org/bugs/?47324 I also made a second file for nano that I got working on ubuntu (for example there is no "normal" color) and added some screen shots :) Thanks @rbberger and @markeganfuller !

**Pull request merged**
