### PR TITLE
Add shell highlighting to sections in vim.

### PR DESCRIPTION
**Pull request by markeganfuller**
* Remove old shell highlighting
* Remove old string highlighting
* Tidy line lengths
* Include vim's shell highlighting
* Highlight `%help` contents

cc: @rbberger @vsoch 

screenshot_2018-05-31_16-52-01

### CODE REVIEW

**Comment by vsoch** [comment]
Awesome!

**Comment by vsoch** [comment]
Do you want to update one of the photos in the README for vim with your picture then we can merge?

**Comment by markeganfuller** [comment]
Images updated.

**Comment by vsoch** [comment]
Awesome thanks!

**Pull request merged**
